name: Sync with Upstream

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          # Usamos nuestro nuevo token superpoderoso
          token: ${{ secrets.PAT }}

      - name: Sync with upstream using rebase
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://github.com/simstudioai/sim.git
          git fetch upstream --tags
          git fetch upstream main
          git checkout main
          git rebase upstream/main
          git push origin main --force
          git push origin --tags --force
